config/routes.rb
Rails.application.routes.draw do
  root "addresses#index"
  resources :addresses

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
# frozen_string_literal: true

# Address model for storing Json data from weather service
#   and generated_at information
class Address < ApplicationRecord
  delegate :cache_expires_in, :body_empty, to: :class

  validates :input, presence: true
  validates_with JsonBodyValidator, on: :create

  def self.body_empty
    { 'empty' => 'Not Loaded' }.to_json
  end

  # number of minutes to keep current_weather_data cache
  def self.cache_expires_in
    @cache_expires_in ||= 30.minutes
  end

  # callers:
  #   VisualCrossing::Presenter.on_index
  # get the body_hash without updating the cache
  def body_hash
    @body_hash ||= JSON.parse(body || body_empty)
  rescue JSON::ParserError
    logger.error("Rescue ParserError for address.id:#{id}",
                 metric: 'Address/Rescue',
                 criteria: inspect)
    @body_hash = {}
  end

  def cache_refreshed?
    @cache_refreshed
  end

  # request:
  #   Cache the forecast details for 30 minutes for all subsequent requests by zip codes.
  #     Display indicator if result is pulled from cache.
  #   - not able to use Zip Code since VisualCrossing does not always return zip_code
  #   - could add a USPS request with address to get it.
  #   - using update_at as cache_key for now.
  # callers:
  #   Request#on_show
  # if current_weather_data cache expired then
  #   get new weather data and store the
  #   body_json response into body and update
  #   the generated_at, without setting the updated_at
  #   used in the cache key
  # Caches the weather_data body_hash into the cache
  def current_weather_data
    @cache_refreshed = false
    Rails.cache.fetch("#{cache_key_with_version}/current_weather_data", expires_in: cache_expires_in) do
      @cache_refreshed = true
      VisualCrossing::Request.on_current_weather_data(self)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: %i[ show edit update destroy ]

  # GET /addresses or /addresses.json
  def index
    @addresses = Address.order(:generated_at).all.reverse
  end

  # GET /addresses/1 or /addresses/1.json
  def show
    on_show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # POST /addresses or /addresses.json
  def create
    @address = on_create

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: "Address was successfully created." }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    if @address.update(address_params)
      redirect_to @address
    else
      render :edit
    end
  end

  def destroy
    @address.destroy

    redirect_to root_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_address
    @address = Address.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def address_params
    params.require(:address).permit(:input)
  end

  # Create a new address resource
  #   call the weather service
  #   and present the results
  def on_create
    model = Address.new(address_params)
    @presenter = VisualCrossing::Presenter.on_create(model) if model.valid?
    model
  end

  # NOTE: the current_weather_data
  #   will check if the cache has expired and
  #   reload the VisualCrossing weather data
  def on_show
    @presenter = VisualCrossing::Presenter.new(@address.current_weather_data)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SemanticLogger::Loggable

end

app/helpers/addresses_helper.rb
module AddressesHelper
  # https://apidock.com/ruby/DateTime/strftime \
  def ui_in_time_zone_eastern(time_utc)
    "#{time_utc.in_time_zone('Eastern Time (US & Canada)').strftime("%l:%M %P %Z")}"
  end

  def ui_in_zone_epoch(epoch)
    Time.find_zone(@zone).at(epoch).strftime("%l:%M %P %Z")
  end

  def ui_in_zone_hour(hour)
    Time.find_zone(@zone).parse(hour).strftime("%l:%M %P %Z")
  end

  def ui_in_zone_hour_short(hour)
    Time.find_zone(@zone).parse(hour).strftime("%l:%M %P")
  end

  def xas_time_in_zone(key)
    label = Address.human_attribute_name(key)
    "#{label} #{ui_in_zone_epoch(@current_conditions[key])}"
  end

  def format_degrees(value)
    "%.1f" % value
  end

  def as_degrees(value)
    t("degrees_html", temp: format_degrees(value))
  end

  def as_precip_probability(value)
    "%.0f %%" % value
  end

  def as_temp(key)
    value = @current_conditions[key]
    t("#{key}_html", temp: format_degrees(value), scope: [:activerecord, :attributes, :address])
  end

  # key:
  #   temp_html, feels_like_html
  def as_html(key, value)
    t("#{key}_html", value: value, scope: [:activerecord, :attributes, :address])
  end

  def address_locale_format(key)
    Address.human_attribute_name(key).gsub('{%}', '%%')
  end

  # key:
  #   humidity, precip_amount, precip_probability
  def with_format(key, value)
    address_locale_format(key) % value
  end

  def last_updated_at(address)
    epoch = address.body_hash['currentConditions']['datetimeEpoch']
    zone = address.body_hash['timezone']
    Time.find_zone(zone).at(epoch).strftime("%l:%M %P %Z")
  rescue NoMethodError => e
    "n/a"
  end

  def title_address
    "<strong>#{@address.resolved_as}</strong> As of #{ui_in_time_zone_eastern(@address.generated_at)}".html_safe
  end

  def title_current_conditions(epoch)
    "<strong>#{@address.resolved_as}</strong> As of #{ui_in_time_zone_eastern(@address.generated_at)}".html_safe
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_current_conditions.html.erb
<% info = presenter.ui_current_conditions %>
<% scope = [:views, :addresses, :current_conditions] %>
<p>
  <%= t("title_html", time: ui_in_zone_epoch(info[:time_epoch]), scope: scope) %>
</p>
<ul>
  <li><%= as_html(:temp, format_degrees(info[:temp])) %></li>
  <li><%= as_html(:feels_like, format_degrees(info[:feels_like])) %></li>
  <li><%= with_format(:humidity, info[:humidity]) %></li>
  <li><%= with_format(:precip_amount, info[:precip_amount].to_f) %></li>
  <li><%= with_format(:precip_probability, info[:precip_probability]) %></li>
</ul>

app/views/addresses/_for_debug.html.erb
<% if Rails.env.test? %>
  <% weather_data = presenter.weather_data %>
  <p> Shown in Development mode only (Response) </p>
  <p> uri: <%= @address.my_uri %> </p>
  <% if weather_data.is_a?(Hash) %>
    <div class="weather-data-keys">
      <%= ap weather_data.keys, :html => true %>
    </div>
    <div class="weather-data-keys">
      <%= ap weather_data["currentConditions"], :html => true %>
    </div>

    <div class="weather-data-list">
      <%= ap weather_data, :html => true %>
    </div>
  <% else %>
    <div class="weather-data-bad-request">
      <%= weather_data %>
    </div>
  <% end %>
<% end %>

app/views/addresses/_form.html.erb
<%= form_with(model: address) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :input %>
    <%= form.text_field :input, size: "50", placeholder: "ex: Spring Hill, FL" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/_high_low_conditions.html.erb
<% high_low_rows = presenter.ui_high_low_conditions %>
<% scope = [:views, :addresses, :high_low_conditions] %>
<% if high_low_rows.present? %>
  <p><%= t("title_html", scope: scope) %></p>
  <div class="row">
    <div class="column"><%= t("col_type_html", scope: scope) %>&nbsp;</div>
    <div class="column"><%= t("col_mean", scope: scope) %></div>
    <div class="column"><%= t("col_high", scope: scope) %></div>
    <div class="column"><%= t("col_low", scope: scope) %></div>
  </div>
  <% high_low_rows.each do |title, cols| %>
    <div class="row">
      <div class="column"><%= t(title, scope: scope) %></div>
      <div class="column"><%= as_degrees(cols[:mean]) %></div>
      <div class="column"><%= as_degrees(cols[:high]) %></div>
      <div class="column"><%= as_degrees(cols[:low]) %></div>
    </div>
  <% end %>
<% end %>

app/views/addresses/_hourly_information.html.erb
<% hourly_rows = presenter.ui_hourly_information %>
<% scope = [:views, :addresses, :hourly_information] %>
<% if hourly_rows.present? %>
  <p> <%= t("title_html", scope: scope) %> </p>
  <div class="row">
    <div class="column"><%= t("col_hour", scope: scope) %></div>
    <div class="column"><%= t("col_temp", scope: scope) %></div>
    <div class="column"><%= t("col_precip_probability", scope: scope) %></div>
    <div class="column"><%= t("col_conditions", scope: scope) %></div>
    <% hourly_rows.each do |cols| %>
      <div class="column"><%= ui_in_zone_hour_short(cols[:hour]) %></div>
      <div class="column"><%= as_degrees(cols[:temp]) %></div>
      <div class="column"><%= as_precip_probability(cols[:precip_probability]) %></div>
      <div class="column"><%= cols[:conditions] %></div>
    <% end %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>
<% scope = [:views, :addresses, :index] %>
<h1><%= t("title", scope: scope) %></h1>

<table>
  <thead>
    <tr>
      <th><%= t("col_address", scope: scope) %></th>
      <th><%= t("col_as_of", scope: scope) %></th>
      <th><%= t("col_temp", scope: scope) %></th>
      <th><%= t("col_feelslike", scope: scope) %></th>
      <th><%= t("col_precipprob", scope: scope) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <% info = VisualCrossing::Presenter.on_index(address) %>
        <td><%= address.resolved_as %></td>
        <td><%= last_updated_at(address) %></td>
        <td><%= as_degrees(info[:temp]) %></td>
        <td><%= as_degrees(info[:feels_like]) %></td>
        <td><%= as_precip_probability(info[:precip_probability])%></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= button_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Weather Data for Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>
<% @zone = @presenter.time_zone %>

<%= link_to 'Back', addresses_path %>
<% dump = false %>
<% if dump %>
  <ul>
    <li>cache refreshed:<%= @address.cache_refreshed? %> generated as
      of <%= ui_in_time_zone_eastern(@address.generated_at) %></li>
    <% datetime = @presenter.weather_data["currentConditions"]["datetime"] %>
    <% epoch = @presenter.weather_data["currentConditions"]["datetimeEpoch"] %>
    <li><%= "Zone:#{@zone}, datetime:#{datetime}, epoch:#{epoch}" %></li>
    <li> raw_datetime: <%= @presenter.weather_data["currentConditions"]["datetime"] %></li>
    <li> raw_epoch: <%= @presenter.weather_data["currentConditions"]["datetimeEpoch"] %></li>

    <li> datetimeEpoch: <%= ui_in_zone_epoch(epoch) %></li>
    <li> datetime: <%= ui_in_zone_hour(datetime) %></li>
    <li> current: <%= Time.current.in_time_zone(@zone).strftime("%l:%M %P %Z") %></li>
  </ul>
<% end %>

<p><%= title_address %></p>
<p><%= @presenter.weather_data["description"] %></p>

<%= render 'current_conditions', presenter: @presenter %>

<%= render 'high_low_conditions', presenter: @presenter %>

<%= render 'hourly_information', presenter: @presenter %>

<%= render 'for_debug', presenter: @presenter %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>